name: Generate GitHub Readme Stats

on:
  schedule:
    - cron: "0 0 * * *" # runs daily at midnight UTC
  workflow_dispatch: # allows manual run from GitHub

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate Stats
        uses: dzello/github-readme-stats-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          output_dir: .github/readme-stats
          stats_filename: stats.svg
          langs_filename: top-langs.svg

      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .github/readme-stats
          git commit -m "Update readme stats" || echo "No changes"
          git push
